#include "Vulkan3DRenderer.hpp"

// Embedded SPIR-V byte arrays (generated by the shaders custom-target).
#include "motor_vert_spv.h"
#include "motor_frag_spv.h"

#include <imgui_impl_vulkan.h>

#include <array>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <vector>

namespace {

struct Vertex { float pos[3]; float color[3]; };

constexpr VkFormat kColorFormat   = VK_FORMAT_R8G8B8A8_UNORM;
constexpr int     kCylSegStator   = 32;
constexpr int     kCylSegRotor    = 24;
constexpr int     kCylSegShaft    = 12;
constexpr float   kIndicatorRadius = 0.30f;
constexpr float   kIndicatorZ     = 1.30f;

void appendCylinder(std::vector<Vertex>& v,
                    float cx, float cy, float cz,
                    float radius, float halfLen, int segments,
                    float r, float g, float b) {
    const float twoPi = 6.28318530717958647692f;
    for (int side = 0; side < 2; ++side) {
        float z = cz + (side ? -halfLen : halfLen);
        for (int i = 0; i < segments; ++i) {
            int j = (i + 1) % segments;
            float ai = twoPi * i / segments;
            float aj = twoPi * j / segments;
            v.push_back({{cx + radius*std::cos(ai), cy + radius*std::sin(ai), z}, {r, g, b}});
            v.push_back({{cx + radius*std::cos(aj), cy + radius*std::sin(aj), z}, {r, g, b}});
        }
    }
    // Axial edges connecting front/back rings.
    for (int i = 0; i < segments; ++i) {
        float a = 6.28318530717958647692f * i / segments;
        float x = cx + radius * std::cos(a);
        float y = cy + radius * std::sin(a);
        v.push_back({{x, y, cz + halfLen}, {r, g, b}});
        v.push_back({{x, y, cz - halfLen}, {r, g, b}});
    }
}

// 4x4 column-major matrix helpers ---------------------------------------------
using Mat4 = std::array<float, 16>;

Mat4 mat4Identity() {
    Mat4 m{}; for (int i = 0; i < 4; ++i) m[i*5] = 1.f; return m;
}

Mat4 mat4Mul(const Mat4& a, const Mat4& b) {
    Mat4 r{};
    for (int c = 0; c < 4; ++c)
        for (int row = 0; row < 4; ++row) {
            float s = 0;
            for (int k = 0; k < 4; ++k) s += a[k*4 + row] * b[c*4 + k];
            r[c*4 + row] = s;
        }
    return r;
}

Mat4 mat4Perspective(float fovYRad, float aspect, float zNear, float zFar) {
    // Vulkan: depth in [0, 1], y points down in clip space.  We negate
    // P[1][1] so model-space up remains visually up on screen.
    Mat4 m{};
    float f = 1.f / std::tan(fovYRad * 0.5f);
    m[0]  =  f / aspect;
    m[5]  = -f;                    // Y flip for Vulkan
    m[10] =  zFar / (zNear - zFar);
    m[11] = -1.f;
    m[14] =  (zFar * zNear) / (zNear - zFar);
    return m;
}

void cross3(const float a[3], const float b[3], float out[3]) {
    out[0] = a[1]*b[2] - a[2]*b[1];
    out[1] = a[2]*b[0] - a[0]*b[2];
    out[2] = a[0]*b[1] - a[1]*b[0];
}
float dot3(const float a[3], const float b[3]) {
    return a[0]*b[0] + a[1]*b[1] + a[2]*b[2];
}
void norm3(float v[3]) {
    float L = std::sqrt(v[0]*v[0]+v[1]*v[1]+v[2]*v[2]);
    if (L > 1e-6f) { v[0]/=L; v[1]/=L; v[2]/=L; }
}

Mat4 mat4LookAt(const float eye[3], const float target[3], const float up[3]) {
    float f[3] = { target[0]-eye[0], target[1]-eye[1], target[2]-eye[2] };
    norm3(f);
    float s[3]; cross3(f, up, s); norm3(s);
    float u[3]; cross3(s, f, u);
    Mat4 m = mat4Identity();
    m[0]  =  s[0]; m[4]  =  s[1]; m[8]  =  s[2];
    m[1]  =  u[0]; m[5]  =  u[1]; m[9]  =  u[2];
    m[2]  = -f[0]; m[6]  = -f[1]; m[10] = -f[2];
    m[12] = -dot3(s, eye);
    m[13] = -dot3(u, eye);
    m[14] =  dot3(f, eye);
    return m;
}

} // namespace

// ============================================================================
// Lifetime
// ============================================================================
Vulkan3DRenderer::~Vulkan3DRenderer() { shutdown(); }

bool Vulkan3DRenderer::init(VulkanContext& ctx) {
    m_ctx = &ctx;
    if (!createCommandResources()) { shutdown(); return false; }
    if (!createVertexBuffer())     { shutdown(); return false; }
    if (!createRenderPass())       { shutdown(); return false; }
    if (!createPipeline())         { shutdown(); return false; }
    m_ready = true;
    return true;
}

void Vulkan3DRenderer::shutdown() {
    if (!m_ctx) return;
    VkDevice dev = m_ctx->device();
    if (dev != VK_NULL_HANDLE) vkDeviceWaitIdle(dev);

    destroyColorTarget();

    if (m_pipeline)   { vkDestroyPipeline(dev, m_pipeline, nullptr);             m_pipeline = VK_NULL_HANDLE; }
    if (m_pipeLayout) { vkDestroyPipelineLayout(dev, m_pipeLayout, nullptr);     m_pipeLayout = VK_NULL_HANDLE; }
    if (m_renderPass) { vkDestroyRenderPass(dev, m_renderPass, nullptr);         m_renderPass = VK_NULL_HANDLE; }
    if (m_vbo)        { vkDestroyBuffer(dev, m_vbo, nullptr);                    m_vbo = VK_NULL_HANDLE; }
    if (m_vboMem)     { vkFreeMemory(dev, m_vboMem, nullptr);                    m_vboMem = VK_NULL_HANDLE; }
    if (m_fence)      { vkDestroyFence(dev, m_fence, nullptr);                   m_fence = VK_NULL_HANDLE; }
    if (m_cmdPool)    { vkDestroyCommandPool(dev, m_cmdPool, nullptr);           m_cmdPool = VK_NULL_HANDLE; m_cmdBuf = VK_NULL_HANDLE; }

    m_ready = false;
    m_ctx   = nullptr;
}

// ============================================================================
// Helpers
// ============================================================================
uint32_t Vulkan3DRenderer::findMemoryType(uint32_t typeBits,
                                          VkMemoryPropertyFlags props) const {
    VkPhysicalDeviceMemoryProperties mp{};
    vkGetPhysicalDeviceMemoryProperties(m_ctx->physicalDevice(), &mp);
    for (uint32_t i = 0; i < mp.memoryTypeCount; ++i)
        if ((typeBits & (1u << i)) &&
            (mp.memoryTypes[i].propertyFlags & props) == props)
            return i;
    return UINT32_MAX;
}

void Vulkan3DRenderer::uploadToBuffer(VkDeviceMemory mem, VkDeviceSize size,
                                      const void* data) {
    void* p = nullptr;
    vkMapMemory(m_ctx->device(), mem, 0, size, 0, &p);
    std::memcpy(p, data, size);
    vkUnmapMemory(m_ctx->device(), mem);
}

// ============================================================================
// Vertex buffer — motor wireframe + indicator slot at the end
// ============================================================================
void Vulkan3DRenderer::buildBaseVertices() {
    std::vector<Vertex> verts;
    // Stator: faint blue
    appendCylinder(verts, 0,0,0, 1.0f,  1.00f, kCylSegStator, 0.40f, 0.62f, 0.88f);
    // Rotor:  brighter blue
    appendCylinder(verts, 0,0,0, 0.55f, 0.85f, kCylSegRotor,  0.45f, 0.73f, 1.00f);
    // Shaft:  warm
    appendCylinder(verts, 0,0,0.65f, 0.18f, 0.65f, kCylSegShaft, 0.95f, 0.78f, 0.35f);
    // Reserve the last pair for the rotating indicator (overwritten each frame).
    m_indicatorVertexBase = (uint32_t)verts.size();
    verts.push_back({{0.0f,            0.0f,            kIndicatorZ}, {1.00f, 0.85f, 0.20f}});
    verts.push_back({{kIndicatorRadius,0.0f,            kIndicatorZ}, {1.00f, 0.85f, 0.20f}});
    m_vertexCount = (uint32_t)verts.size();
    // Upload to the host-coherent VBO.
    uploadToBuffer(m_vboMem, sizeof(Vertex) * m_vertexCount, verts.data());
}

bool Vulkan3DRenderer::createVertexBuffer() {
    // Worst-case size estimate: 2 * (rings + axial) per cylinder × 3 cylinders + indicator
    const int maxLines = 3 * (2 * kCylSegStator + kCylSegStator) + 2;   // generous
    (void)maxLines;
    const VkDeviceSize sz = sizeof(Vertex) *
        (2 * (kCylSegStator * 2 + kCylSegStator) +
         2 * (kCylSegRotor  * 2 + kCylSegRotor)  +
         2 * (kCylSegShaft  * 2 + kCylSegShaft)  + 2);

    VkBufferCreateInfo bi{};
    bi.sType       = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    bi.size        = sz;
    bi.usage       = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
    bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateBuffer(m_ctx->device(), &bi, nullptr, &m_vbo) != VK_SUCCESS)
        return false;

    VkMemoryRequirements mr{};
    vkGetBufferMemoryRequirements(m_ctx->device(), m_vbo, &mr);
    VkMemoryAllocateInfo ai{};
    ai.sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    ai.allocationSize  = mr.size;
    ai.memoryTypeIndex = findMemoryType(
        mr.memoryTypeBits,
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    if (ai.memoryTypeIndex == UINT32_MAX) return false;
    if (vkAllocateMemory(m_ctx->device(), &ai, nullptr, &m_vboMem) != VK_SUCCESS) return false;
    if (vkBindBufferMemory(m_ctx->device(), m_vbo, m_vboMem, 0) != VK_SUCCESS)    return false;

    buildBaseVertices();
    return true;
}

void Vulkan3DRenderer::updateIndicatorVertex(float shaftAngle) {
    // Patch only the second indicator vertex; the centre stays at (0,0,z).
    Vertex tip{{
        kIndicatorRadius * std::cos(shaftAngle),
        kIndicatorRadius * std::sin(shaftAngle),
        kIndicatorZ
    }, {1.00f, 0.85f, 0.20f}};
    void* p = nullptr;
    VkDeviceSize off = sizeof(Vertex) * (m_indicatorVertexBase + 1);
    vkMapMemory(m_ctx->device(), m_vboMem, off, sizeof(Vertex), 0, &p);
    std::memcpy(p, &tip, sizeof(Vertex));
    vkUnmapMemory(m_ctx->device(), m_vboMem);
}

// ============================================================================
// Render pass — 1 color attachment, external dependencies for safe sampling
// from ImGui's main pass after our submit completes.
// ============================================================================
bool Vulkan3DRenderer::createRenderPass() {
    VkAttachmentDescription color{};
    color.format         = kColorFormat;
    color.samples        = VK_SAMPLE_COUNT_1_BIT;
    color.loadOp         = VK_ATTACHMENT_LOAD_OP_CLEAR;
    color.storeOp        = VK_ATTACHMENT_STORE_OP_STORE;
    color.stencilLoadOp  = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
    color.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    color.initialLayout  = VK_IMAGE_LAYOUT_UNDEFINED;
    color.finalLayout    = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;

    VkAttachmentReference colorRef{};
    colorRef.attachment = 0;
    colorRef.layout     = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

    VkSubpassDescription sub{};
    sub.pipelineBindPoint    = VK_PIPELINE_BIND_POINT_GRAPHICS;
    sub.colorAttachmentCount = 1;
    sub.pColorAttachments    = &colorRef;

    VkSubpassDependency deps[2]{};
    // EXTERNAL → 0 : wait for any previous reads of this image to finish
    // before we write to it.
    deps[0].srcSubpass    = VK_SUBPASS_EXTERNAL;
    deps[0].dstSubpass    = 0;
    deps[0].srcStageMask  = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
    deps[0].dstStageMask  = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    deps[0].srcAccessMask = VK_ACCESS_SHADER_READ_BIT;
    deps[0].dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    // 0 → EXTERNAL : ensure our writes are visible to the ImGui fragment
    // shader sampling on the next submission of the same queue.
    deps[1].srcSubpass    = 0;
    deps[1].dstSubpass    = VK_SUBPASS_EXTERNAL;
    deps[1].srcStageMask  = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    deps[1].dstStageMask  = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
    deps[1].srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    deps[1].dstAccessMask = VK_ACCESS_SHADER_READ_BIT;

    VkRenderPassCreateInfo rp{};
    rp.sType           = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
    rp.attachmentCount = 1;
    rp.pAttachments    = &color;
    rp.subpassCount    = 1;
    rp.pSubpasses      = &sub;
    rp.dependencyCount = 2;
    rp.pDependencies   = deps;
    return vkCreateRenderPass(m_ctx->device(), &rp, nullptr, &m_renderPass) == VK_SUCCESS;
}

// ============================================================================
// Graphics pipeline (line topology + push constants + vertex layout)
// ============================================================================
bool Vulkan3DRenderer::createPipeline() {
    VkDevice dev = m_ctx->device();

    auto makeModule = [&](const uint32_t* code, size_t count) -> VkShaderModule {
        VkShaderModuleCreateInfo m{};
        m.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        m.codeSize = count * sizeof(uint32_t);
        m.pCode    = code;
        VkShaderModule out = VK_NULL_HANDLE;
        vkCreateShaderModule(dev, &m, nullptr, &out);
        return out;
    };

    VkShaderModule vs = makeModule(kMotorVertSpv, kMotorVertSpv_count);
    VkShaderModule fs = makeModule(kMotorFragSpv, kMotorFragSpv_count);
    if (!vs || !fs) return false;

    VkPipelineShaderStageCreateInfo stages[2]{};
    stages[0].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage  = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vs;
    stages[0].pName  = "main";
    stages[1].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage  = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = fs;
    stages[1].pName  = "main";

    // Vertex layout: vec3 pos + vec3 color, 24-byte stride.
    VkVertexInputBindingDescription vbBind{};
    vbBind.binding   = 0;
    vbBind.stride    = sizeof(Vertex);
    vbBind.inputRate = VK_VERTEX_INPUT_RATE_VERTEX;

    VkVertexInputAttributeDescription vbAttr[2]{};
    vbAttr[0].location = 0;
    vbAttr[0].binding  = 0;
    vbAttr[0].format   = VK_FORMAT_R32G32B32_SFLOAT;
    vbAttr[0].offset   = offsetof(Vertex, pos);
    vbAttr[1].location = 1;
    vbAttr[1].binding  = 0;
    vbAttr[1].format   = VK_FORMAT_R32G32B32_SFLOAT;
    vbAttr[1].offset   = offsetof(Vertex, color);

    VkPipelineVertexInputStateCreateInfo vi{};
    vi.sType                           = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
    vi.vertexBindingDescriptionCount   = 1;
    vi.pVertexBindingDescriptions      = &vbBind;
    vi.vertexAttributeDescriptionCount = 2;
    vi.pVertexAttributeDescriptions    = vbAttr;

    VkPipelineInputAssemblyStateCreateInfo ia{};
    ia.sType    = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    ia.topology = VK_PRIMITIVE_TOPOLOGY_LINE_LIST;

    VkPipelineViewportStateCreateInfo vp{};
    vp.sType         = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    vp.viewportCount = 1;
    vp.scissorCount  = 1;

    VkPipelineRasterizationStateCreateInfo rs{};
    rs.sType       = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    rs.polygonMode = VK_POLYGON_MODE_LINE;
    rs.cullMode    = VK_CULL_MODE_NONE;
    rs.frontFace   = VK_FRONT_FACE_COUNTER_CLOCKWISE;
    rs.lineWidth   = 1.0f;

    VkPipelineMultisampleStateCreateInfo ms{};
    ms.sType                = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    VkPipelineColorBlendAttachmentState cba{};
    cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                         VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
    cba.blendEnable    = VK_FALSE;
    VkPipelineColorBlendStateCreateInfo cb{};
    cb.sType           = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    cb.attachmentCount = 1;
    cb.pAttachments    = &cba;

    VkDynamicState dyn[2] = { VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR };
    VkPipelineDynamicStateCreateInfo ds{};
    ds.sType             = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    ds.dynamicStateCount = 2;
    ds.pDynamicStates    = dyn;

    VkPushConstantRange pcr{};
    pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
    pcr.offset     = 0;
    pcr.size       = 128;          // mat4 viewProj + mat4 model

    VkPipelineLayoutCreateInfo pl{};
    pl.sType                  = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    pl.pushConstantRangeCount = 1;
    pl.pPushConstantRanges    = &pcr;
    if (vkCreatePipelineLayout(dev, &pl, nullptr, &m_pipeLayout) != VK_SUCCESS) {
        vkDestroyShaderModule(dev, vs, nullptr);
        vkDestroyShaderModule(dev, fs, nullptr);
        return false;
    }

    VkGraphicsPipelineCreateInfo pp{};
    pp.sType               = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    pp.stageCount          = 2;
    pp.pStages             = stages;
    pp.pVertexInputState   = &vi;
    pp.pInputAssemblyState = &ia;
    pp.pViewportState      = &vp;
    pp.pRasterizationState = &rs;
    pp.pMultisampleState   = &ms;
    pp.pColorBlendState    = &cb;
    pp.pDynamicState       = &ds;
    pp.layout              = m_pipeLayout;
    pp.renderPass          = m_renderPass;
    pp.subpass             = 0;
    VkResult r = vkCreateGraphicsPipelines(dev, VK_NULL_HANDLE, 1, &pp, nullptr, &m_pipeline);

    vkDestroyShaderModule(dev, vs, nullptr);
    vkDestroyShaderModule(dev, fs, nullptr);
    return r == VK_SUCCESS;
}

// ============================================================================
// Command resources (pool + buffer + fence)
// ============================================================================
bool Vulkan3DRenderer::createCommandResources() {
    VkCommandPoolCreateInfo pi{};
    pi.sType            = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
    pi.flags            = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
    pi.queueFamilyIndex = m_ctx->graphicsFamily();
    if (vkCreateCommandPool(m_ctx->device(), &pi, nullptr, &m_cmdPool) != VK_SUCCESS)
        return false;

    VkCommandBufferAllocateInfo ci{};
    ci.sType              = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    ci.commandPool        = m_cmdPool;
    ci.level              = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    ci.commandBufferCount = 1;
    if (vkAllocateCommandBuffers(m_ctx->device(), &ci, &m_cmdBuf) != VK_SUCCESS)
        return false;

    VkFenceCreateInfo fi{};
    fi.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
    fi.flags = VK_FENCE_CREATE_SIGNALED_BIT;
    return vkCreateFence(m_ctx->device(), &fi, nullptr, &m_fence) == VK_SUCCESS;
}

// ============================================================================
// Offscreen color target
// ============================================================================
bool Vulkan3DRenderer::createColorTarget() {
    VkDevice dev = m_ctx->device();

    VkImageCreateInfo ii{};
    ii.sType         = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    ii.imageType     = VK_IMAGE_TYPE_2D;
    ii.format        = kColorFormat;
    ii.extent        = { m_extent.width, m_extent.height, 1 };
    ii.mipLevels     = 1;
    ii.arrayLayers   = 1;
    ii.samples       = VK_SAMPLE_COUNT_1_BIT;
    ii.tiling        = VK_IMAGE_TILING_OPTIMAL;
    ii.usage         = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
    ii.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    ii.sharingMode   = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateImage(dev, &ii, nullptr, &m_image) != VK_SUCCESS) return false;

    VkMemoryRequirements mr{};
    vkGetImageMemoryRequirements(dev, m_image, &mr);
    VkMemoryAllocateInfo ai{};
    ai.sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    ai.allocationSize  = mr.size;
    ai.memoryTypeIndex = findMemoryType(mr.memoryTypeBits,
                                        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (ai.memoryTypeIndex == UINT32_MAX)                              return false;
    if (vkAllocateMemory(dev, &ai, nullptr, &m_imageMem) != VK_SUCCESS) return false;
    if (vkBindImageMemory(dev, m_image, m_imageMem, 0) != VK_SUCCESS)   return false;

    VkImageViewCreateInfo vi{};
    vi.sType    = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    vi.image    = m_image;
    vi.viewType = VK_IMAGE_VIEW_TYPE_2D;
    vi.format   = kColorFormat;
    vi.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    vi.subresourceRange.levelCount = 1;
    vi.subresourceRange.layerCount = 1;
    if (vkCreateImageView(dev, &vi, nullptr, &m_imageView) != VK_SUCCESS) return false;

    VkSamplerCreateInfo si{};
    si.sType        = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
    si.magFilter    = VK_FILTER_LINEAR;
    si.minFilter    = VK_FILTER_LINEAR;
    si.addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    si.addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    si.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    if (vkCreateSampler(dev, &si, nullptr, &m_sampler) != VK_SUCCESS) return false;

    VkFramebufferCreateInfo fi{};
    fi.sType           = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
    fi.renderPass      = m_renderPass;
    fi.attachmentCount = 1;
    fi.pAttachments    = &m_imageView;
    fi.width           = m_extent.width;
    fi.height          = m_extent.height;
    fi.layers          = 1;
    if (vkCreateFramebuffer(dev, &fi, nullptr, &m_framebuffer) != VK_SUCCESS) return false;

    // Register the texture with ImGui's Vulkan backend so the panel can
    // pass the descriptor set to ImGui::Image.
    m_imguiTexture = (ImTextureID)ImGui_ImplVulkan_AddTexture(
        m_sampler, m_imageView, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
    return true;
}

void Vulkan3DRenderer::destroyColorTarget() {
    if (!m_ctx) return;
    VkDevice dev = m_ctx->device();
    if (dev == VK_NULL_HANDLE) return;

    if (m_imguiTexture) {
        ImGui_ImplVulkan_RemoveTexture((VkDescriptorSet)m_imguiTexture);
        m_imguiTexture = 0;
    }
    if (m_framebuffer) { vkDestroyFramebuffer(dev, m_framebuffer, nullptr); m_framebuffer = VK_NULL_HANDLE; }
    if (m_sampler)     { vkDestroySampler   (dev, m_sampler,     nullptr); m_sampler     = VK_NULL_HANDLE; }
    if (m_imageView)   { vkDestroyImageView (dev, m_imageView,   nullptr); m_imageView   = VK_NULL_HANDLE; }
    if (m_image)       { vkDestroyImage     (dev, m_image,       nullptr); m_image       = VK_NULL_HANDLE; }
    if (m_imageMem)    { vkFreeMemory       (dev, m_imageMem,    nullptr); m_imageMem    = VK_NULL_HANDLE; }
}

void Vulkan3DRenderer::resize(uint32_t width, uint32_t height) {
    if (!m_ctx || !m_ready) return;
    if (width  == 0 || height == 0) return;
    if (width == m_extent.width && height == m_extent.height) return;

    vkDeviceWaitIdle(m_ctx->device());
    destroyColorTarget();
    m_extent = { width, height };
    if (!createColorTarget()) {
        // Best-effort: leave the renderer in a non-ready state.
        m_extent = { 0, 0 };
    }
}

// ============================================================================
// render — record + submit one frame's worth of commands. Returns once the
// submission is queued; the EXTERNAL→0/0→EXTERNAL subpass dependencies in
// the render pass take care of the cross-submission memory barrier so the
// ImGui main pass (same queue) can sample the image safely.
// ============================================================================
void Vulkan3DRenderer::render(float shaftAngle, float azimuthDeg,
                              float elevationDeg, float zoom) {
    if (!ready()) return;

    VkDevice dev = m_ctx->device();
    vkWaitForFences(dev, 1, &m_fence, VK_TRUE, UINT64_MAX);
    vkResetFences  (dev, 1, &m_fence);

    updateIndicatorVertex(shaftAngle);

    // Compute orbit camera matrices.
    constexpr float kDeg = 3.14159265f / 180.0f;
    float azR = azimuthDeg   * kDeg;
    float elR = elevationDeg * kDeg;
    float distance = std::max(0.05f, 6.0f / std::max(0.01f, zoom));
    float eye[3] = {
        distance * std::cos(elR) * std::sin(azR),
        distance * std::sin(elR),
        distance * std::cos(elR) * std::cos(azR)
    };
    float target[3] = { 0.f, 0.f, 0.f };
    float up[3]     = { 0.f, 1.f, 0.f };
    Mat4 view  = mat4LookAt(eye, target, up);
    float aspect = m_extent.height ? (float)m_extent.width / m_extent.height : 1.f;
    Mat4 proj  = mat4Perspective(45.f * kDeg, aspect, 0.1f, 100.f);
    Mat4 vp    = mat4Mul(proj, view);
    Mat4 model = mat4Identity();

    // ---- record ----
    vkResetCommandBuffer(m_cmdBuf, 0);
    VkCommandBufferBeginInfo bi{};
    bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(m_cmdBuf, &bi);

    VkClearValue clr{};
    clr.color = {{ 0.055f, 0.059f, 0.080f, 1.0f }};
    VkRenderPassBeginInfo rb{};
    rb.sType             = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
    rb.renderPass        = m_renderPass;
    rb.framebuffer       = m_framebuffer;
    rb.renderArea.offset = { 0, 0 };
    rb.renderArea.extent = m_extent;
    rb.clearValueCount   = 1;
    rb.pClearValues      = &clr;
    vkCmdBeginRenderPass(m_cmdBuf, &rb, VK_SUBPASS_CONTENTS_INLINE);

    VkViewport vpv{};
    vpv.x = 0.f; vpv.y = 0.f;
    vpv.width  = (float)m_extent.width;
    vpv.height = (float)m_extent.height;
    vpv.maxDepth = 1.f;
    vkCmdSetViewport(m_cmdBuf, 0, 1, &vpv);
    VkRect2D sc{ {0,0}, m_extent };
    vkCmdSetScissor (m_cmdBuf, 0, 1, &sc);

    vkCmdBindPipeline(m_cmdBuf, VK_PIPELINE_BIND_POINT_GRAPHICS, m_pipeline);
    VkDeviceSize offs = 0;
    vkCmdBindVertexBuffers(m_cmdBuf, 0, 1, &m_vbo, &offs);

    float pc[32];
    std::memcpy(pc,      vp.data(),    16 * sizeof(float));
    std::memcpy(pc + 16, model.data(), 16 * sizeof(float));
    vkCmdPushConstants(m_cmdBuf, m_pipeLayout,
                       VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(pc), pc);

    vkCmdDraw(m_cmdBuf, m_vertexCount, 1, 0, 0);

    vkCmdEndRenderPass(m_cmdBuf);
    vkEndCommandBuffer(m_cmdBuf);

    VkSubmitInfo si{};
    si.sType              = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers    = &m_cmdBuf;
    vkQueueSubmit(m_ctx->graphicsQueue(), 1, &si, m_fence);
}
