#include "Vulkan3DRenderer.hpp"

// Embedded SPIR-V byte arrays (generated by the shaders custom-target).
#include "motor_vert_spv.h"
#include "motor_frag_spv.h"
#include "asset_vert_spv.h"
#include "asset_frag_spv.h"

#include <imgui_impl_vulkan.h>

#include <array>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <vector>

namespace {

// Aliased to the public class type so the file-local helpers can build
// vectors of vertices without needing to qualify the class scope.
using Vertex = Vulkan3DRenderer::Vertex;

constexpr VkFormat kColorFormat    = VK_FORMAT_R8G8B8A8_UNORM;
constexpr int     kCylSegStator    = 32;
constexpr int     kCylSegRotor     = 24;
constexpr int     kCylSegShaft     = 12;
constexpr float   kIndicatorRadius = 0.30f;
constexpr float   kIndicatorZ      = 1.30f;

// Cámara perspectiva del visualizador 3D — los valores son los típicos
// para un editor 3D de escritorio (FOV moderado, near corto para que el
// usuario pueda acercarse, far amplio para que la escena no se recorte
// al hacer zoom-out).
constexpr float   kCameraFovDeg    = 45.f;
constexpr float   kCameraNear      = 0.1f;
constexpr float   kCameraFar       = 100.f;
constexpr float   kDegToRad        = 3.14159265f / 180.0f;

void appendCylinder(std::vector<Vertex>& v,
                    float cx, float cy, float cz,
                    float radius, float halfLen, int segments,
                    float r, float g, float b) {
    const float twoPi = 6.28318530717958647692f;
    for (int side = 0; side < 2; ++side) {
        float z = cz + (side ? -halfLen : halfLen);
        for (int i = 0; i < segments; ++i) {
            int j = (i + 1) % segments;
            float ai = twoPi * i / segments;
            float aj = twoPi * j / segments;
            v.push_back({{cx + radius*std::cos(ai), cy + radius*std::sin(ai), z}, {r, g, b}});
            v.push_back({{cx + radius*std::cos(aj), cy + radius*std::sin(aj), z}, {r, g, b}});
        }
    }
    // Axial edges connecting front/back rings.
    for (int i = 0; i < segments; ++i) {
        float a = 6.28318530717958647692f * i / segments;
        float x = cx + radius * std::cos(a);
        float y = cy + radius * std::sin(a);
        v.push_back({{x, y, cz + halfLen}, {r, g, b}});
        v.push_back({{x, y, cz - halfLen}, {r, g, b}});
    }
}

// 4x4 column-major matrix helpers ---------------------------------------------
using Mat4 = std::array<float, 16>;

Mat4 mat4Identity() {
    Mat4 m{}; for (int i = 0; i < 4; ++i) m[i*5] = 1.f; return m;
}

Mat4 mat4Mul(const Mat4& a, const Mat4& b) {
    Mat4 r{};
    for (int c = 0; c < 4; ++c)
        for (int row = 0; row < 4; ++row) {
            float s = 0;
            for (int k = 0; k < 4; ++k) s += a[k*4 + row] * b[c*4 + k];
            r[c*4 + row] = s;
        }
    return r;
}

Mat4 mat4Perspective(float fovYRad, float aspect, float zNear, float zFar) {
    // Vulkan: depth in [0, 1], y points down in clip space.  We negate
    // P[1][1] so model-space up remains visually up on screen.
    Mat4 m{};
    float f = 1.f / std::tan(fovYRad * 0.5f);
    m[0]  =  f / aspect;
    m[5]  = -f;                    // Y flip for Vulkan
    m[10] =  zFar / (zNear - zFar);
    m[11] = -1.f;
    m[14] =  (zFar * zNear) / (zNear - zFar);
    return m;
}

void cross3(const float a[3], const float b[3], float out[3]) {
    out[0] = a[1]*b[2] - a[2]*b[1];
    out[1] = a[2]*b[0] - a[0]*b[2];
    out[2] = a[0]*b[1] - a[1]*b[0];
}
float dot3(const float a[3], const float b[3]) {
    return a[0]*b[0] + a[1]*b[1] + a[2]*b[2];
}
void norm3(float v[3]) {
    float L = std::sqrt(v[0]*v[0]+v[1]*v[1]+v[2]*v[2]);
    if (L > 1e-6f) { v[0]/=L; v[1]/=L; v[2]/=L; }
}

Mat4 mat4LookAt(const float eye[3], const float target[3], const float up[3]) {
    float f[3] = { target[0]-eye[0], target[1]-eye[1], target[2]-eye[2] };
    norm3(f);
    float s[3]; cross3(f, up, s); norm3(s);
    float u[3]; cross3(s, f, u);
    Mat4 m = mat4Identity();
    m[0]  =  s[0]; m[4]  =  s[1]; m[8]  =  s[2];
    m[1]  =  u[0]; m[5]  =  u[1]; m[9]  =  u[2];
    m[2]  = -f[0]; m[6]  = -f[1]; m[10] = -f[2];
    m[12] = -dot3(s, eye);
    m[13] = -dot3(u, eye);
    m[14] =  dot3(f, eye);
    return m;
}

} // namespace

// ============================================================================
// Lifetime
// ============================================================================
Vulkan3DRenderer::~Vulkan3DRenderer() { shutdown(); }

bool Vulkan3DRenderer::init(VulkanContext& ctx) {
    m_ctx = &ctx;
    if (!createCommandResources()) { shutdown(); return false; }
    if (!createVertexBuffer())     { shutdown(); return false; }
    if (!createRenderPass())       { shutdown(); return false; }
    if (!createPipeline())         { shutdown(); return false; }
    if (!createSolidPipeline())    { shutdown(); return false; }
    if (!createWirePipeline())     { shutdown(); return false; }
    m_ready = true;
    return true;
}

void Vulkan3DRenderer::shutdown() {
    if (!m_ctx) return;
    VkDevice dev = m_ctx->device();
    if (dev != VK_NULL_HANDLE) vkDeviceWaitIdle(dev);

    destroyColorTarget();

    if (m_wirePipeline)    { vkDestroyPipeline(dev, m_wirePipeline, nullptr);        m_wirePipeline = VK_NULL_HANDLE; }
    if (m_solidPipeline)   { vkDestroyPipeline(dev, m_solidPipeline, nullptr);       m_solidPipeline = VK_NULL_HANDLE; }
    if (m_solidPipeLayout) { vkDestroyPipelineLayout(dev, m_solidPipeLayout, nullptr); m_solidPipeLayout = VK_NULL_HANDLE; }
    if (m_pipeline)   { vkDestroyPipeline(dev, m_pipeline, nullptr);             m_pipeline = VK_NULL_HANDLE; }
    if (m_pipeLayout) { vkDestroyPipelineLayout(dev, m_pipeLayout, nullptr);     m_pipeLayout = VK_NULL_HANDLE; }
    if (m_renderPass) { vkDestroyRenderPass(dev, m_renderPass, nullptr);         m_renderPass = VK_NULL_HANDLE; }
    if (m_vbo)        { vkDestroyBuffer(dev, m_vbo, nullptr);                    m_vbo = VK_NULL_HANDLE; }
    if (m_vboMem)     { vkFreeMemory(dev, m_vboMem, nullptr);                    m_vboMem = VK_NULL_HANDLE; }
    if (m_assetVbo)   { vkDestroyBuffer(dev, m_assetVbo, nullptr);               m_assetVbo = VK_NULL_HANDLE; }
    if (m_assetVboMem){ vkFreeMemory(dev, m_assetVboMem, nullptr);               m_assetVboMem = VK_NULL_HANDLE; }
    if (m_assetIbo)   { vkDestroyBuffer(dev, m_assetIbo, nullptr);               m_assetIbo = VK_NULL_HANDLE; }
    if (m_assetIboMem){ vkFreeMemory(dev, m_assetIboMem, nullptr);               m_assetIboMem = VK_NULL_HANDLE; }
    if (m_fence)      { vkDestroyFence(dev, m_fence, nullptr);                   m_fence = VK_NULL_HANDLE; }
    if (m_cmdPool)    { vkDestroyCommandPool(dev, m_cmdPool, nullptr);           m_cmdPool = VK_NULL_HANDLE; m_cmdBuf = VK_NULL_HANDLE; }

    m_ready = false;
    m_ctx   = nullptr;
}

// ============================================================================
// Helpers
// ============================================================================
uint32_t Vulkan3DRenderer::findMemoryType(uint32_t typeBits,
                                          VkMemoryPropertyFlags props) const {
    VkPhysicalDeviceMemoryProperties mp{};
    vkGetPhysicalDeviceMemoryProperties(m_ctx->physicalDevice(), &mp);
    for (uint32_t i = 0; i < mp.memoryTypeCount; ++i)
        if ((typeBits & (1u << i)) &&
            (mp.memoryTypes[i].propertyFlags & props) == props)
            return i;
    return UINT32_MAX;
}

void Vulkan3DRenderer::uploadToBuffer(VkDeviceMemory mem, VkDeviceSize size,
                                      const void* data) {
    void* p = nullptr;
    vkMapMemory(m_ctx->device(), mem, 0, size, 0, &p);
    std::memcpy(p, data, size);
    vkUnmapMemory(m_ctx->device(), mem);
}

// ============================================================================
// Vertex buffer — motor wireframe + indicator slot at the end
// ============================================================================
void Vulkan3DRenderer::buildBaseVertices() {
    std::vector<Vertex> verts;
    // Stator: faint blue
    appendCylinder(verts, 0,0,0, 1.0f,  1.00f, kCylSegStator, 0.40f, 0.62f, 0.88f);
    // Rotor:  brighter blue
    appendCylinder(verts, 0,0,0, 0.55f, 0.85f, kCylSegRotor,  0.45f, 0.73f, 1.00f);
    // Shaft:  warm
    appendCylinder(verts, 0,0,0.65f, 0.18f, 0.65f, kCylSegShaft, 0.95f, 0.78f, 0.35f);
    // Reserve the last pair for the rotating indicator (overwritten each frame).
    m_indicatorVertexBase = (uint32_t)verts.size();
    verts.push_back({{0.0f,            0.0f,            kIndicatorZ}, {1.00f, 0.85f, 0.20f}});
    verts.push_back({{kIndicatorRadius,0.0f,            kIndicatorZ}, {1.00f, 0.85f, 0.20f}});
    m_vertexCount = (uint32_t)verts.size();
    // Upload to the host-coherent VBO. Also keep an undeformed copy so
    // the deformation update can rewrite the VBO each frame.
    m_baseMesh = verts;
    uploadToBuffer(m_vboMem, sizeof(Vertex) * m_vertexCount, verts.data());
}

bool Vulkan3DRenderer::createVertexBuffer() {
    // Initial size — comfortably covers the legacy DC motor. Procedural
    // meshes may exceed this; uploadProceduralWireframe reallocates the
    // buffer when needed.
    const VkDeviceSize sz = sizeof(Vertex) *
        (2 * (kCylSegStator * 2 + kCylSegStator) +
         2 * (kCylSegRotor  * 2 + kCylSegRotor)  +
         2 * (kCylSegShaft  * 2 + kCylSegShaft)  + 2);

    VkBufferCreateInfo bi{};
    bi.sType       = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    bi.size        = sz;
    bi.usage       = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
    bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateBuffer(m_ctx->device(), &bi, nullptr, &m_vbo) != VK_SUCCESS)
        return false;

    VkMemoryRequirements mr{};
    vkGetBufferMemoryRequirements(m_ctx->device(), m_vbo, &mr);
    VkMemoryAllocateInfo ai{};
    ai.sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    ai.allocationSize  = mr.size;
    ai.memoryTypeIndex = findMemoryType(
        mr.memoryTypeBits,
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    if (ai.memoryTypeIndex == UINT32_MAX) return false;
    if (vkAllocateMemory(m_ctx->device(), &ai, nullptr, &m_vboMem) != VK_SUCCESS) return false;
    if (vkBindBufferMemory(m_ctx->device(), m_vbo, m_vboMem, 0) != VK_SUCCESS)    return false;
    m_vboCapacityBytes = sz;

    buildBaseVertices();
    return true;
}

void Vulkan3DRenderer::rebuildLegacyMotor() {
    if (!m_ready) return;
    buildBaseVertices();
}

bool Vulkan3DRenderer::uploadProceduralWireframe(
        const std::vector<float>& verts3,
        const std::vector<std::array<int, 2>>& edges,
        float r, float g, float b) {
    if (!m_ready) return false;
    const int vertCount = static_cast<int>(verts3.size() / 3);

    std::vector<Vertex> packed;
    packed.reserve(edges.size() * 2 + 2);
    for (const auto& e : edges) {
        for (int idx : { e[0], e[1] }) {
            if (idx < 0 || idx >= vertCount) {
                packed.push_back({{ 0, 0, 0 }, { r, g, b }});
                continue;
            }
            packed.push_back({{ verts3[3 * idx + 0],
                                verts3[3 * idx + 1],
                                verts3[3 * idx + 2] }, { r, g, b }});
        }
    }
    // Indicator pair at the tail. updateIndicatorVertex still owns the
    // second one — we just seed both to the default (centre, +x tip).
    uint32_t indicatorBase = static_cast<uint32_t>(packed.size());
    packed.push_back({{ 0.0f,             0.0f, kIndicatorZ }, { 1.00f, 0.85f, 0.20f }});
    packed.push_back({{ kIndicatorRadius, 0.0f, kIndicatorZ }, { 1.00f, 0.85f, 0.20f }});

    VkDeviceSize neededBytes = sizeof(Vertex) * packed.size();
    if (neededBytes > m_vboCapacityBytes) {
        // Wait for any in-flight frame using the current VBO before
        // freeing it. ImGui's main pass samples the offscreen image but
        // not the VBO, so a queue idle is sufficient.
        vkQueueWaitIdle(m_ctx->graphicsQueue());
        vkDestroyBuffer(m_ctx->device(), m_vbo, nullptr);
        vkFreeMemory  (m_ctx->device(), m_vboMem, nullptr);
        m_vbo    = VK_NULL_HANDLE;
        m_vboMem = VK_NULL_HANDLE;

        VkDeviceSize newCap = std::max<VkDeviceSize>(neededBytes,
                                                     m_vboCapacityBytes * 2);
        VkBufferCreateInfo bi{};
        bi.sType       = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
        bi.size        = newCap;
        bi.usage       = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
        bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
        if (vkCreateBuffer(m_ctx->device(), &bi, nullptr, &m_vbo) != VK_SUCCESS)
            return false;

        VkMemoryRequirements mr{};
        vkGetBufferMemoryRequirements(m_ctx->device(), m_vbo, &mr);
        VkMemoryAllocateInfo ai{};
        ai.sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
        ai.allocationSize  = mr.size;
        ai.memoryTypeIndex = findMemoryType(
            mr.memoryTypeBits,
            VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
            VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
        if (ai.memoryTypeIndex == UINT32_MAX) return false;
        if (vkAllocateMemory(m_ctx->device(), &ai, nullptr, &m_vboMem) != VK_SUCCESS)
            return false;
        if (vkBindBufferMemory(m_ctx->device(), m_vbo, m_vboMem, 0) != VK_SUCCESS)
            return false;
        m_vboCapacityBytes = newCap;
    }

    uploadToBuffer(m_vboMem, neededBytes, packed.data());
    m_baseMesh            = std::move(packed);
    m_vertexCount         = static_cast<uint32_t>(m_baseMesh.size());
    m_indicatorVertexBase = indicatorBase;
    return true;
}

void Vulkan3DRenderer::setDeformation(bool active, float freq,
                                      float modeOrder, float amplitude) {
    // Stash the new state for the next render() call. If we just
    // transitioned active → inactive, mark the VBO dirty so the next
    // frame restores the undeformed base mesh once before going quiet.
    if (m_deformActive && !active) m_deformDirty = true;
    m_deformActive    = active;
    m_deformFreq      = freq;
    m_deformMode      = modeOrder;
    m_deformAmplitude = amplitude;
}

// ============================================================================
// Asset mesh upload (device-asset triangles).  VBO+IBO host-visible
// coherent — el mesh es chico (decenas a miles de tris) y solo se sube
// cuando cambia el asset, así que el overhead de la copia es despreciable.
// Re-aloca cuando el tamaño excede la capacidad cacheada (vkQueueWaitIdle
// para no liberar buffers en uso).
// ============================================================================
namespace {
bool allocHostBuffer(VulkanContext& ctx, VkBuffer& outBuf, VkDeviceMemory& outMem,
                     VkDeviceSize size, VkBufferUsageFlags usage,
                     uint32_t (*findMemType)(VulkanContext&, uint32_t, VkMemoryPropertyFlags))
{
    VkBufferCreateInfo bi{};
    bi.sType       = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    bi.size        = size;
    bi.usage       = usage;
    bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateBuffer(ctx.device(), &bi, nullptr, &outBuf) != VK_SUCCESS) return false;

    VkMemoryRequirements mr{};
    vkGetBufferMemoryRequirements(ctx.device(), outBuf, &mr);
    VkMemoryAllocateInfo ai{};
    ai.sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    ai.allocationSize  = mr.size;
    ai.memoryTypeIndex = findMemType(ctx, mr.memoryTypeBits,
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    if (ai.memoryTypeIndex == UINT32_MAX) return false;
    if (vkAllocateMemory(ctx.device(), &ai, nullptr, &outMem) != VK_SUCCESS) return false;
    return vkBindBufferMemory(ctx.device(), outBuf, outMem, 0) == VK_SUCCESS;
}
uint32_t findMemTypeWrapper(VulkanContext& ctx, uint32_t bits, VkMemoryPropertyFlags p) {
    VkPhysicalDeviceMemoryProperties mp{};
    vkGetPhysicalDeviceMemoryProperties(ctx.physicalDevice(), &mp);
    for (uint32_t i = 0; i < mp.memoryTypeCount; ++i)
        if ((bits & (1u << i)) && (mp.memoryTypes[i].propertyFlags & p) == p)
            return i;
    return UINT32_MAX;
}
}  // namespace

bool Vulkan3DRenderer::uploadAssetMesh(const std::vector<float>&    positions,
                                       const std::vector<float>&    normals,
                                       const std::vector<uint32_t>& indices,
                                       float tintR, float tintG, float tintB) {
    if (!m_ready) return false;
    if (positions.empty() || indices.empty() || positions.size() != normals.size())
        return false;
    if (positions.size() % 3 != 0 || indices.size() % 3 != 0) return false;

    const size_t vertexCount = positions.size() / 3;
    std::vector<SolidVertex> packed(vertexCount);
    for (size_t i = 0; i < vertexCount; ++i) {
        packed[i].pos[0]    = positions[3*i + 0];
        packed[i].pos[1]    = positions[3*i + 1];
        packed[i].pos[2]    = positions[3*i + 2];
        packed[i].normal[0] = normals[3*i + 0];
        packed[i].normal[1] = normals[3*i + 1];
        packed[i].normal[2] = normals[3*i + 2];
    }

    const VkDeviceSize vboBytes = sizeof(SolidVertex) * packed.size();
    const VkDeviceSize iboBytes = sizeof(uint32_t)    * indices.size();

    auto reallocIfNeeded = [&](VkBuffer& buf, VkDeviceMemory& mem,
                               VkDeviceSize& cap, VkDeviceSize needed,
                               VkBufferUsageFlags usage) -> bool {
        if (needed <= cap && buf != VK_NULL_HANDLE) return true;
        vkQueueWaitIdle(m_ctx->graphicsQueue());
        if (buf) { vkDestroyBuffer(m_ctx->device(), buf, nullptr); buf = VK_NULL_HANDLE; }
        if (mem) { vkFreeMemory   (m_ctx->device(), mem, nullptr); mem = VK_NULL_HANDLE; }
        VkDeviceSize newCap = std::max(needed, cap * 2);
        if (!allocHostBuffer(*m_ctx, buf, mem, newCap, usage, findMemTypeWrapper))
            return false;
        cap = newCap;
        return true;
    };

    if (!reallocIfNeeded(m_assetVbo, m_assetVboMem, m_assetVboCapBytes,
                         vboBytes, VK_BUFFER_USAGE_VERTEX_BUFFER_BIT)) return false;
    if (!reallocIfNeeded(m_assetIbo, m_assetIboMem, m_assetIboCapBytes,
                         iboBytes, VK_BUFFER_USAGE_INDEX_BUFFER_BIT))  return false;

    uploadToBuffer(m_assetVboMem, vboBytes, packed.data());
    uploadToBuffer(m_assetIboMem, iboBytes, indices.data());

    m_assetIndexCount = static_cast<uint32_t>(indices.size());
    m_assetActive     = true;
    m_assetTint[0] = tintR; m_assetTint[1] = tintG; m_assetTint[2] = tintB;
    return true;
}

void Vulkan3DRenderer::clearAsset() {
    m_assetActive     = false;
    m_assetIndexCount = 0;
    // Los buffers se conservan para no perder la capacidad si se vuelve
    // a cargar un asset de tamaño similar.  Liberación final ocurre en
    // shutdown().
}

void Vulkan3DRenderer::updateIndicatorVertex(float shaftAngle) {
    // Patch only the second indicator vertex; the centre stays at (0,0,z).
    Vertex tip{{
        kIndicatorRadius * std::cos(shaftAngle),
        kIndicatorRadius * std::sin(shaftAngle),
        kIndicatorZ
    }, {1.00f, 0.85f, 0.20f}};
    void* p = nullptr;
    VkDeviceSize off = sizeof(Vertex) * (m_indicatorVertexBase + 1);
    vkMapMemory(m_ctx->device(), m_vboMem, off, sizeof(Vertex), 0, &p);
    std::memcpy(p, &tip, sizeof(Vertex));
    vkUnmapMemory(m_ctx->device(), m_vboMem);
}

// ============================================================================
// Render pass — 1 color attachment, external dependencies for safe sampling
// from ImGui's main pass after our submit completes.
// ============================================================================
bool Vulkan3DRenderer::createRenderPass() {
    VkAttachmentDescription atts[2]{};
    // [0] color
    atts[0].format         = kColorFormat;
    atts[0].samples        = VK_SAMPLE_COUNT_1_BIT;
    atts[0].loadOp         = VK_ATTACHMENT_LOAD_OP_CLEAR;
    atts[0].storeOp        = VK_ATTACHMENT_STORE_OP_STORE;
    atts[0].stencilLoadOp  = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
    atts[0].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    atts[0].initialLayout  = VK_IMAGE_LAYOUT_UNDEFINED;
    atts[0].finalLayout    = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
    // [1] depth
    atts[1].format         = m_depthFormat;
    atts[1].samples        = VK_SAMPLE_COUNT_1_BIT;
    atts[1].loadOp         = VK_ATTACHMENT_LOAD_OP_CLEAR;
    atts[1].storeOp        = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    atts[1].stencilLoadOp  = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
    atts[1].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    atts[1].initialLayout  = VK_IMAGE_LAYOUT_UNDEFINED;
    atts[1].finalLayout    = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

    VkAttachmentReference colorRef{};
    colorRef.attachment = 0;
    colorRef.layout     = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    VkAttachmentReference depthRef{};
    depthRef.attachment = 1;
    depthRef.layout     = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

    VkSubpassDescription sub{};
    sub.pipelineBindPoint       = VK_PIPELINE_BIND_POINT_GRAPHICS;
    sub.colorAttachmentCount    = 1;
    sub.pColorAttachments       = &colorRef;
    sub.pDepthStencilAttachment = &depthRef;

    VkSubpassDependency deps[2]{};
    // EXTERNAL → 0 : wait for any previous reads of this image to finish
    // before we write to it. Stage incluye EARLY_FRAGMENT_TESTS para el
    // depth attachment.
    deps[0].srcSubpass    = VK_SUBPASS_EXTERNAL;
    deps[0].dstSubpass    = 0;
    deps[0].srcStageMask  = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
    deps[0].dstStageMask  = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT |
                            VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;
    deps[0].srcAccessMask = VK_ACCESS_SHADER_READ_BIT;
    deps[0].dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT |
                            VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
    // 0 → EXTERNAL : ensure our writes are visible to the ImGui fragment
    // shader sampling on the next submission of the same queue.
    deps[1].srcSubpass    = 0;
    deps[1].dstSubpass    = VK_SUBPASS_EXTERNAL;
    deps[1].srcStageMask  = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    deps[1].dstStageMask  = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
    deps[1].srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    deps[1].dstAccessMask = VK_ACCESS_SHADER_READ_BIT;

    VkRenderPassCreateInfo rp{};
    rp.sType           = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
    rp.attachmentCount = 2;
    rp.pAttachments    = atts;
    rp.subpassCount    = 1;
    rp.pSubpasses      = &sub;
    rp.dependencyCount = 2;
    rp.pDependencies   = deps;
    return vkCreateRenderPass(m_ctx->device(), &rp, nullptr, &m_renderPass) == VK_SUCCESS;
}

// ============================================================================
// Graphics pipeline (line topology + push constants + vertex layout)
// ============================================================================
bool Vulkan3DRenderer::createPipeline() {
    VkDevice dev = m_ctx->device();

    auto makeModule = [&](const uint32_t* code, size_t count) -> VkShaderModule {
        VkShaderModuleCreateInfo m{};
        m.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        m.codeSize = count * sizeof(uint32_t);
        m.pCode    = code;
        VkShaderModule out = VK_NULL_HANDLE;
        vkCreateShaderModule(dev, &m, nullptr, &out);
        return out;
    };

    VkShaderModule vs = makeModule(kMotorVertSpv, kMotorVertSpv_count);
    VkShaderModule fs = makeModule(kMotorFragSpv, kMotorFragSpv_count);
    if (!vs || !fs) return false;

    VkPipelineShaderStageCreateInfo stages[2]{};
    stages[0].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage  = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vs;
    stages[0].pName  = "main";
    stages[1].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage  = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = fs;
    stages[1].pName  = "main";

    // Vertex layout: vec3 pos + vec3 color, 24-byte stride.
    VkVertexInputBindingDescription vbBind{};
    vbBind.binding   = 0;
    vbBind.stride    = sizeof(Vertex);
    vbBind.inputRate = VK_VERTEX_INPUT_RATE_VERTEX;

    VkVertexInputAttributeDescription vbAttr[2]{};
    vbAttr[0].location = 0;
    vbAttr[0].binding  = 0;
    vbAttr[0].format   = VK_FORMAT_R32G32B32_SFLOAT;
    vbAttr[0].offset   = offsetof(Vertex, pos);
    vbAttr[1].location = 1;
    vbAttr[1].binding  = 0;
    vbAttr[1].format   = VK_FORMAT_R32G32B32_SFLOAT;
    vbAttr[1].offset   = offsetof(Vertex, color);

    VkPipelineVertexInputStateCreateInfo vi{};
    vi.sType                           = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
    vi.vertexBindingDescriptionCount   = 1;
    vi.pVertexBindingDescriptions      = &vbBind;
    vi.vertexAttributeDescriptionCount = 2;
    vi.pVertexAttributeDescriptions    = vbAttr;

    VkPipelineInputAssemblyStateCreateInfo ia{};
    ia.sType    = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    ia.topology = VK_PRIMITIVE_TOPOLOGY_LINE_LIST;

    VkPipelineViewportStateCreateInfo vp{};
    vp.sType         = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    vp.viewportCount = 1;
    vp.scissorCount  = 1;

    VkPipelineRasterizationStateCreateInfo rs{};
    rs.sType       = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    rs.polygonMode = VK_POLYGON_MODE_LINE;
    rs.cullMode    = VK_CULL_MODE_NONE;
    rs.frontFace   = VK_FRONT_FACE_COUNTER_CLOCKWISE;
    rs.lineWidth   = 1.0f;

    VkPipelineMultisampleStateCreateInfo ms{};
    ms.sType                = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    VkPipelineColorBlendAttachmentState cba{};
    cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                         VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
    cba.blendEnable    = VK_FALSE;
    VkPipelineColorBlendStateCreateInfo cb{};
    cb.sType           = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    cb.attachmentCount = 1;
    cb.pAttachments    = &cba;

    VkDynamicState dyn[2] = { VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR };
    VkPipelineDynamicStateCreateInfo ds{};
    ds.sType             = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    ds.dynamicStateCount = 2;
    ds.pDynamicStates    = dyn;

    VkPushConstantRange pcr{};
    pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
    pcr.offset     = 0;
    pcr.size       = 128;          // mat4 viewProj + mat4 model

    VkPipelineLayoutCreateInfo pl{};
    pl.sType                  = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    pl.pushConstantRangeCount = 1;
    pl.pPushConstantRanges    = &pcr;
    if (vkCreatePipelineLayout(dev, &pl, nullptr, &m_pipeLayout) != VK_SUCCESS) {
        vkDestroyShaderModule(dev, vs, nullptr);
        vkDestroyShaderModule(dev, fs, nullptr);
        return false;
    }

    // El render pass tiene depth attachment; el pipeline de líneas
    // debe declarar VkPipelineDepthStencilStateCreateInfo aunque no use
    // depth (Vulkan exige que matchee la subpass).  depthTest=FALSE,
    // depthWrite=FALSE para que las líneas no se escondan tras el solid.
    VkPipelineDepthStencilStateCreateInfo dss{};
    dss.sType                 = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
    dss.depthTestEnable       = VK_FALSE;
    dss.depthWriteEnable      = VK_FALSE;
    dss.depthCompareOp        = VK_COMPARE_OP_ALWAYS;
    dss.depthBoundsTestEnable = VK_FALSE;
    dss.stencilTestEnable     = VK_FALSE;

    VkGraphicsPipelineCreateInfo pp{};
    pp.sType               = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    pp.stageCount          = 2;
    pp.pStages             = stages;
    pp.pVertexInputState   = &vi;
    pp.pInputAssemblyState = &ia;
    pp.pViewportState      = &vp;
    pp.pRasterizationState = &rs;
    pp.pMultisampleState   = &ms;
    pp.pDepthStencilState  = &dss;
    pp.pColorBlendState    = &cb;
    pp.pDynamicState       = &ds;
    pp.layout              = m_pipeLayout;
    pp.renderPass          = m_renderPass;
    pp.subpass             = 0;
    VkResult r = vkCreateGraphicsPipelines(dev, VK_NULL_HANDLE, 1, &pp, nullptr, &m_pipeline);

    vkDestroyShaderModule(dev, vs, nullptr);
    vkDestroyShaderModule(dev, fs, nullptr);
    return r == VK_SUCCESS;
}

// ============================================================================
// Solid pipeline (triangle list + Lambert + depth test) — para DeviceAsset.
// Convive con el line pipeline bajo el mismo render pass; cuál se bindea lo
// decide render() según m_assetActive.  Las normales del vertex layout (vec3)
// vienen del View3DPanel cuando aplana el asset; el push constant incluye
// tint para que el housing herede el color del View3DThermalSink.
// ============================================================================
bool Vulkan3DRenderer::createSolidPipeline() {
    VkDevice dev = m_ctx->device();

    auto makeModule = [&](const uint32_t* code, size_t count) -> VkShaderModule {
        VkShaderModuleCreateInfo m{};
        m.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        m.codeSize = count * sizeof(uint32_t);
        m.pCode    = code;
        VkShaderModule out = VK_NULL_HANDLE;
        vkCreateShaderModule(dev, &m, nullptr, &out);
        return out;
    };

    VkShaderModule vs = makeModule(kAssetVertSpv, kAssetVertSpv_count);
    VkShaderModule fs = makeModule(kAssetFragSpv, kAssetFragSpv_count);
    if (!vs || !fs) return false;

    VkPipelineShaderStageCreateInfo stages[2]{};
    stages[0].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage  = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vs;
    stages[0].pName  = "main";
    stages[1].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage  = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = fs;
    stages[1].pName  = "main";

    // Vertex layout: vec3 pos + vec3 normal, 24-byte stride.
    VkVertexInputBindingDescription vbBind{};
    vbBind.binding   = 0;
    vbBind.stride    = sizeof(SolidVertex);
    vbBind.inputRate = VK_VERTEX_INPUT_RATE_VERTEX;

    VkVertexInputAttributeDescription vbAttr[2]{};
    vbAttr[0].location = 0;
    vbAttr[0].binding  = 0;
    vbAttr[0].format   = VK_FORMAT_R32G32B32_SFLOAT;
    vbAttr[0].offset   = offsetof(SolidVertex, pos);
    vbAttr[1].location = 1;
    vbAttr[1].binding  = 0;
    vbAttr[1].format   = VK_FORMAT_R32G32B32_SFLOAT;
    vbAttr[1].offset   = offsetof(SolidVertex, normal);

    VkPipelineVertexInputStateCreateInfo vi{};
    vi.sType                           = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
    vi.vertexBindingDescriptionCount   = 1;
    vi.pVertexBindingDescriptions      = &vbBind;
    vi.vertexAttributeDescriptionCount = 2;
    vi.pVertexAttributeDescriptions    = vbAttr;

    VkPipelineInputAssemblyStateCreateInfo ia{};
    ia.sType    = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

    VkPipelineViewportStateCreateInfo vp{};
    vp.sType         = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    vp.viewportCount = 1;
    vp.scissorCount  = 1;

    VkPipelineRasterizationStateCreateInfo rs{};
    rs.sType       = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    rs.polygonMode = VK_POLYGON_MODE_FILL;
    // Sin cull face — los assets de glTF en el repo no garantizan winding
    // consistente.  Si en el futuro se normalizan, cambiar a BACK.
    rs.cullMode    = VK_CULL_MODE_NONE;
    rs.frontFace   = VK_FRONT_FACE_COUNTER_CLOCKWISE;
    rs.lineWidth   = 1.0f;

    VkPipelineMultisampleStateCreateInfo ms{};
    ms.sType                = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    VkPipelineDepthStencilStateCreateInfo dss{};
    dss.sType                 = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
    dss.depthTestEnable       = VK_TRUE;
    dss.depthWriteEnable      = VK_TRUE;
    dss.depthCompareOp        = VK_COMPARE_OP_LESS;
    dss.depthBoundsTestEnable = VK_FALSE;
    dss.stencilTestEnable     = VK_FALSE;

    VkPipelineColorBlendAttachmentState cba{};
    cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                         VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
    cba.blendEnable    = VK_FALSE;
    VkPipelineColorBlendStateCreateInfo cb{};
    cb.sType           = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    cb.attachmentCount = 1;
    cb.pAttachments    = &cba;

    VkDynamicState dyn[2] = { VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR };
    VkPipelineDynamicStateCreateInfo ds{};
    ds.sType             = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    ds.dynamicStateCount = 2;
    ds.pDynamicStates    = dyn;

    // Push constant: mat4 viewProj (64) + mat4 model (64) + vec4 tint (16) = 144 B.
    // 144 está dentro del mínimo garantizado de 128 B?  No — Vulkan exige al
    // menos 128.  Para mantener compatibilidad amplia, dejamos tint en vec4
    // (16 B) y ajustamos a 144 — todos los GPUs modernos soportan ≥128 y la
    // mayoría 256.  Si esto da problemas con drivers viejos, mover tint a
    // un UBO descriptor set.
    VkPushConstantRange pcr{};
    pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
    pcr.offset     = 0;
    pcr.size       = 144;

    VkPipelineLayoutCreateInfo pl{};
    pl.sType                  = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    pl.pushConstantRangeCount = 1;
    pl.pPushConstantRanges    = &pcr;
    if (vkCreatePipelineLayout(dev, &pl, nullptr, &m_solidPipeLayout) != VK_SUCCESS) {
        vkDestroyShaderModule(dev, vs, nullptr);
        vkDestroyShaderModule(dev, fs, nullptr);
        return false;
    }

    VkGraphicsPipelineCreateInfo pp{};
    pp.sType               = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    pp.stageCount          = 2;
    pp.pStages             = stages;
    pp.pVertexInputState   = &vi;
    pp.pInputAssemblyState = &ia;
    pp.pViewportState      = &vp;
    pp.pRasterizationState = &rs;
    pp.pMultisampleState   = &ms;
    pp.pDepthStencilState  = &dss;
    pp.pColorBlendState    = &cb;
    pp.pDynamicState       = &ds;
    pp.layout              = m_solidPipeLayout;
    pp.renderPass          = m_renderPass;
    pp.subpass             = 0;
    VkResult r = vkCreateGraphicsPipelines(dev, VK_NULL_HANDLE, 1, &pp, nullptr, &m_solidPipeline);

    vkDestroyShaderModule(dev, vs, nullptr);
    vkDestroyShaderModule(dev, fs, nullptr);
    return r == VK_SUCCESS;
}

// ============================================================================
// Wire pipeline — comparte vertex layout y push-constants con el solid
// pipeline, sólo cambia polygonMode=LINE y agrega depthBias para que en
// modo "Both" las aristas no compitan con el solid en z-fighting.
// Reutiliza m_solidPipeLayout (mismo push constant).
// ============================================================================
bool Vulkan3DRenderer::createWirePipeline() {
    VkDevice dev = m_ctx->device();

    auto makeModule = [&](const uint32_t* code, size_t count) -> VkShaderModule {
        VkShaderModuleCreateInfo m{};
        m.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        m.codeSize = count * sizeof(uint32_t);
        m.pCode    = code;
        VkShaderModule out = VK_NULL_HANDLE;
        vkCreateShaderModule(dev, &m, nullptr, &out);
        return out;
    };

    VkShaderModule vs = makeModule(kAssetVertSpv, kAssetVertSpv_count);
    VkShaderModule fs = makeModule(kAssetFragSpv, kAssetFragSpv_count);
    if (!vs || !fs) return false;

    VkPipelineShaderStageCreateInfo stages[2]{};
    stages[0].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage  = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vs;
    stages[0].pName  = "main";
    stages[1].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage  = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = fs;
    stages[1].pName  = "main";

    VkVertexInputBindingDescription vbBind{};
    vbBind.binding   = 0;
    vbBind.stride    = sizeof(SolidVertex);
    vbBind.inputRate = VK_VERTEX_INPUT_RATE_VERTEX;

    VkVertexInputAttributeDescription vbAttr[2]{};
    vbAttr[0].location = 0;
    vbAttr[0].binding  = 0;
    vbAttr[0].format   = VK_FORMAT_R32G32B32_SFLOAT;
    vbAttr[0].offset   = offsetof(SolidVertex, pos);
    vbAttr[1].location = 1;
    vbAttr[1].binding  = 0;
    vbAttr[1].format   = VK_FORMAT_R32G32B32_SFLOAT;
    vbAttr[1].offset   = offsetof(SolidVertex, normal);

    VkPipelineVertexInputStateCreateInfo vi{};
    vi.sType                           = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
    vi.vertexBindingDescriptionCount   = 1;
    vi.pVertexBindingDescriptions      = &vbBind;
    vi.vertexAttributeDescriptionCount = 2;
    vi.pVertexAttributeDescriptions    = vbAttr;

    VkPipelineInputAssemblyStateCreateInfo ia{};
    ia.sType    = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;  // 3 vértices/tri → LINE pinta sus 3 aristas

    VkPipelineViewportStateCreateInfo vp{};
    vp.sType         = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    vp.viewportCount = 1;
    vp.scissorCount  = 1;

    VkPipelineRasterizationStateCreateInfo rs{};
    rs.sType                   = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    rs.polygonMode             = VK_POLYGON_MODE_LINE;   // <-- la diferencia clave
    rs.cullMode                = VK_CULL_MODE_NONE;
    rs.frontFace               = VK_FRONT_FACE_COUNTER_CLOCKWISE;
    rs.lineWidth               = 1.0f;
    // Bias hacia la cámara para que en modo Both las líneas queden por
    // encima del solid sin pelearse con el depth buffer.
    rs.depthBiasEnable         = VK_TRUE;
    rs.depthBiasConstantFactor = -1.0f;
    rs.depthBiasSlopeFactor    = -1.0f;

    VkPipelineMultisampleStateCreateInfo ms{};
    ms.sType                = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    VkPipelineDepthStencilStateCreateInfo dss{};
    dss.sType                 = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
    dss.depthTestEnable       = VK_TRUE;
    dss.depthWriteEnable      = VK_TRUE;
    dss.depthCompareOp        = VK_COMPARE_OP_LESS_OR_EQUAL;  // ≤ para coexistir con solid
    dss.depthBoundsTestEnable = VK_FALSE;
    dss.stencilTestEnable     = VK_FALSE;

    VkPipelineColorBlendAttachmentState cba{};
    cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                         VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
    cba.blendEnable    = VK_FALSE;
    VkPipelineColorBlendStateCreateInfo cb{};
    cb.sType           = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    cb.attachmentCount = 1;
    cb.pAttachments    = &cba;

    VkDynamicState dyn[2] = { VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR };
    VkPipelineDynamicStateCreateInfo ds{};
    ds.sType             = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    ds.dynamicStateCount = 2;
    ds.pDynamicStates    = dyn;

    VkGraphicsPipelineCreateInfo pp{};
    pp.sType               = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    pp.stageCount          = 2;
    pp.pStages             = stages;
    pp.pVertexInputState   = &vi;
    pp.pInputAssemblyState = &ia;
    pp.pViewportState      = &vp;
    pp.pRasterizationState = &rs;
    pp.pMultisampleState   = &ms;
    pp.pDepthStencilState  = &dss;
    pp.pColorBlendState    = &cb;
    pp.pDynamicState       = &ds;
    pp.layout              = m_solidPipeLayout;   // reuse
    pp.renderPass          = m_renderPass;
    pp.subpass             = 0;
    VkResult r = vkCreateGraphicsPipelines(dev, VK_NULL_HANDLE, 1, &pp, nullptr, &m_wirePipeline);

    vkDestroyShaderModule(dev, vs, nullptr);
    vkDestroyShaderModule(dev, fs, nullptr);
    return r == VK_SUCCESS;
}

// ============================================================================
// Command resources (pool + buffer + fence)
// ============================================================================
bool Vulkan3DRenderer::createCommandResources() {
    VkCommandPoolCreateInfo pi{};
    pi.sType            = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
    pi.flags            = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
    pi.queueFamilyIndex = m_ctx->graphicsFamily();
    if (vkCreateCommandPool(m_ctx->device(), &pi, nullptr, &m_cmdPool) != VK_SUCCESS)
        return false;

    VkCommandBufferAllocateInfo ci{};
    ci.sType              = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    ci.commandPool        = m_cmdPool;
    ci.level              = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    ci.commandBufferCount = 1;
    if (vkAllocateCommandBuffers(m_ctx->device(), &ci, &m_cmdBuf) != VK_SUCCESS)
        return false;

    VkFenceCreateInfo fi{};
    fi.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
    fi.flags = VK_FENCE_CREATE_SIGNALED_BIT;
    return vkCreateFence(m_ctx->device(), &fi, nullptr, &m_fence) == VK_SUCCESS;
}

// ============================================================================
// Offscreen color target
// ============================================================================
bool Vulkan3DRenderer::createColorTarget() {
    VkDevice dev = m_ctx->device();

    VkImageCreateInfo ii{};
    ii.sType         = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    ii.imageType     = VK_IMAGE_TYPE_2D;
    ii.format        = kColorFormat;
    ii.extent        = { m_extent.width, m_extent.height, 1 };
    ii.mipLevels     = 1;
    ii.arrayLayers   = 1;
    ii.samples       = VK_SAMPLE_COUNT_1_BIT;
    ii.tiling        = VK_IMAGE_TILING_OPTIMAL;
    ii.usage         = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
    ii.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    ii.sharingMode   = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateImage(dev, &ii, nullptr, &m_image) != VK_SUCCESS) return false;

    VkMemoryRequirements mr{};
    vkGetImageMemoryRequirements(dev, m_image, &mr);
    VkMemoryAllocateInfo ai{};
    ai.sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    ai.allocationSize  = mr.size;
    ai.memoryTypeIndex = findMemoryType(mr.memoryTypeBits,
                                        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (ai.memoryTypeIndex == UINT32_MAX)                              return false;
    if (vkAllocateMemory(dev, &ai, nullptr, &m_imageMem) != VK_SUCCESS) return false;
    if (vkBindImageMemory(dev, m_image, m_imageMem, 0) != VK_SUCCESS)   return false;

    VkImageViewCreateInfo vi{};
    vi.sType    = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    vi.image    = m_image;
    vi.viewType = VK_IMAGE_VIEW_TYPE_2D;
    vi.format   = kColorFormat;
    vi.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    vi.subresourceRange.levelCount = 1;
    vi.subresourceRange.layerCount = 1;
    if (vkCreateImageView(dev, &vi, nullptr, &m_imageView) != VK_SUCCESS) return false;

    VkSamplerCreateInfo si{};
    si.sType        = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
    si.magFilter    = VK_FILTER_LINEAR;
    si.minFilter    = VK_FILTER_LINEAR;
    si.addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    si.addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    si.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    if (vkCreateSampler(dev, &si, nullptr, &m_sampler) != VK_SUCCESS) return false;

    // Depth attachment vive en paralelo al color; ambos van al framebuffer.
    if (!createDepthTarget()) return false;

    VkImageView views[2] = { m_imageView, m_depthView };
    VkFramebufferCreateInfo fi{};
    fi.sType           = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
    fi.renderPass      = m_renderPass;
    fi.attachmentCount = 2;
    fi.pAttachments    = views;
    fi.width           = m_extent.width;
    fi.height          = m_extent.height;
    fi.layers          = 1;
    if (vkCreateFramebuffer(dev, &fi, nullptr, &m_framebuffer) != VK_SUCCESS) return false;

    // Register the texture with ImGui's Vulkan backend so the panel can
    // pass the descriptor set to ImGui::Image.
    m_imguiTexture = (ImTextureID)ImGui_ImplVulkan_AddTexture(
        m_sampler, m_imageView, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
    return true;
}

// ============================================================================
// Offscreen depth target — separado del color para SRP.  Recreado junto con
// el color (en resize); su lifetime está atado al framebuffer.
// ============================================================================
bool Vulkan3DRenderer::createDepthTarget() {
    VkDevice dev = m_ctx->device();

    VkImageCreateInfo ii{};
    ii.sType         = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    ii.imageType     = VK_IMAGE_TYPE_2D;
    ii.format        = m_depthFormat;
    ii.extent        = { m_extent.width, m_extent.height, 1 };
    ii.mipLevels     = 1;
    ii.arrayLayers   = 1;
    ii.samples       = VK_SAMPLE_COUNT_1_BIT;
    ii.tiling        = VK_IMAGE_TILING_OPTIMAL;
    ii.usage         = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;
    ii.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    ii.sharingMode   = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateImage(dev, &ii, nullptr, &m_depthImage) != VK_SUCCESS) return false;

    VkMemoryRequirements mr{};
    vkGetImageMemoryRequirements(dev, m_depthImage, &mr);
    VkMemoryAllocateInfo ai{};
    ai.sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    ai.allocationSize  = mr.size;
    ai.memoryTypeIndex = findMemoryType(mr.memoryTypeBits,
                                        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (ai.memoryTypeIndex == UINT32_MAX)                                return false;
    if (vkAllocateMemory(dev, &ai, nullptr, &m_depthMem) != VK_SUCCESS)  return false;
    if (vkBindImageMemory(dev, m_depthImage, m_depthMem, 0) != VK_SUCCESS) return false;

    VkImageViewCreateInfo vi{};
    vi.sType    = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    vi.image    = m_depthImage;
    vi.viewType = VK_IMAGE_VIEW_TYPE_2D;
    vi.format   = m_depthFormat;
    vi.subresourceRange.aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT;
    vi.subresourceRange.levelCount = 1;
    vi.subresourceRange.layerCount = 1;
    return vkCreateImageView(dev, &vi, nullptr, &m_depthView) == VK_SUCCESS;
}

void Vulkan3DRenderer::destroyDepthTarget() {
    if (!m_ctx) return;
    VkDevice dev = m_ctx->device();
    if (dev == VK_NULL_HANDLE) return;
    if (m_depthView)  { vkDestroyImageView(dev, m_depthView,  nullptr); m_depthView  = VK_NULL_HANDLE; }
    if (m_depthImage) { vkDestroyImage    (dev, m_depthImage, nullptr); m_depthImage = VK_NULL_HANDLE; }
    if (m_depthMem)   { vkFreeMemory      (dev, m_depthMem,   nullptr); m_depthMem   = VK_NULL_HANDLE; }
}

void Vulkan3DRenderer::destroyColorTarget() {
    if (!m_ctx) return;
    VkDevice dev = m_ctx->device();
    if (dev == VK_NULL_HANDLE) return;

    if (m_imguiTexture) {
        ImGui_ImplVulkan_RemoveTexture((VkDescriptorSet)m_imguiTexture);
        m_imguiTexture = 0;
    }
    if (m_framebuffer) { vkDestroyFramebuffer(dev, m_framebuffer, nullptr); m_framebuffer = VK_NULL_HANDLE; }
    destroyDepthTarget();
    if (m_sampler)     { vkDestroySampler   (dev, m_sampler,     nullptr); m_sampler     = VK_NULL_HANDLE; }
    if (m_imageView)   { vkDestroyImageView (dev, m_imageView,   nullptr); m_imageView   = VK_NULL_HANDLE; }
    if (m_image)       { vkDestroyImage     (dev, m_image,       nullptr); m_image       = VK_NULL_HANDLE; }
    if (m_imageMem)    { vkFreeMemory       (dev, m_imageMem,    nullptr); m_imageMem    = VK_NULL_HANDLE; }
}

void Vulkan3DRenderer::resize(uint32_t width, uint32_t height) {
    if (!m_ctx || !m_ready) return;
    if (width  == 0 || height == 0) return;
    if (width == m_extent.width && height == m_extent.height) return;

    vkDeviceWaitIdle(m_ctx->device());
    destroyColorTarget();
    m_extent = { width, height };
    if (!createColorTarget()) {
        // Best-effort: leave the renderer in a non-ready state.
        m_extent = { 0, 0 };
    }
}

// ============================================================================
// render — record + submit one frame's worth of commands. Returns once the
// submission is queued; the EXTERNAL→0/0→EXTERNAL subpass dependencies in
// the render pass take care of the cross-submission memory barrier so the
// ImGui main pass (same queue) can sample the image safely.
// ============================================================================
void Vulkan3DRenderer::render(float shaftAngle, float azimuthDeg,
                              float elevationDeg, float zoom) {
    if (!ready()) return;

    VkDevice dev = m_ctx->device();
    vkWaitForFences(dev, 1, &m_fence, VK_TRUE, UINT64_MAX);
    vkResetFences  (dev, 1, &m_fence);

    updateIndicatorVertex(shaftAngle);

    // Per-frame deformation overlay. The VBO is host-coherent and the
    // previous frame's GPU work has already retired by the time we get
    // here (the vkWaitForFences above), so the memcpy below is
    // hazard-free — same pattern as updateIndicatorVertex.
    if (m_deformActive && !m_baseMesh.empty()) {
        using clock = std::chrono::steady_clock;
        static const auto t0 = clock::now();
        float t = std::chrono::duration<float>(clock::now() - t0).count();
        float phase = 2.0f * 3.14159265f * m_deformFreq * t;
        float envelope = std::sin(phase);

        std::vector<Vertex> deformed = m_baseMesh;
        // Leave the indicator pair untouched.
        size_t nDeform = m_baseMesh.size() >= 2
                            ? m_baseMesh.size() - 2
                            : m_baseMesh.size();
        for (size_t i = 0; i < nDeform; ++i) {
            float x = m_baseMesh[i].pos[0];
            float y = m_baseMesh[i].pos[1];
            float r = std::sqrt(x * x + y * y);
            if (r < 1e-3f) continue;            // axis vertices stay fixed
            float theta = std::atan2(y, x);
            float dr = m_deformAmplitude * std::cos(m_deformMode * theta)
                                          * envelope;
            float scale = 1.0f + dr / r;
            deformed[i].pos[0] = x * scale;
            deformed[i].pos[1] = y * scale;
            // z unchanged
        }
        uploadToBuffer(m_vboMem,
                       sizeof(Vertex) * deformed.size(),
                       deformed.data());
    } else if (m_deformDirty) {
        // Just transitioned to inactive — restore the undeformed VBO
        // once and stop touching it.
        uploadToBuffer(m_vboMem,
                       sizeof(Vertex) * m_baseMesh.size(),
                       m_baseMesh.data());
        m_deformDirty = false;
    }

    // Compute orbit camera matrices.
    float azR = azimuthDeg   * kDegToRad;
    float elR = elevationDeg * kDegToRad;
    float distance = std::max(0.05f, 6.0f / std::max(0.01f, zoom));
    float eye[3] = {
        distance * std::cos(elR) * std::sin(azR),
        distance * std::sin(elR),
        distance * std::cos(elR) * std::cos(azR)
    };
    float target[3] = { 0.f, 0.f, 0.f };
    float up[3]     = { 0.f, 1.f, 0.f };
    Mat4 view  = mat4LookAt(eye, target, up);
    float aspect = m_extent.height ? (float)m_extent.width / m_extent.height : 1.f;
    Mat4 proj  = mat4Perspective(kCameraFovDeg * kDegToRad, aspect,
                                 kCameraNear, kCameraFar);
    Mat4 vp    = mat4Mul(proj, view);
    Mat4 model = mat4Identity();

    // ---- record ----
    vkResetCommandBuffer(m_cmdBuf, 0);
    VkCommandBufferBeginInfo bi{};
    bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(m_cmdBuf, &bi);

    VkClearValue clrs[2]{};
    clrs[0].color        = {{ 0.055f, 0.059f, 0.080f, 1.0f }};
    clrs[1].depthStencil = { 1.0f, 0 };
    VkRenderPassBeginInfo rb{};
    rb.sType             = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
    rb.renderPass        = m_renderPass;
    rb.framebuffer       = m_framebuffer;
    rb.renderArea.offset = { 0, 0 };
    rb.renderArea.extent = m_extent;
    rb.clearValueCount   = 2;
    rb.pClearValues      = clrs;
    vkCmdBeginRenderPass(m_cmdBuf, &rb, VK_SUBPASS_CONTENTS_INLINE);

    VkViewport vpv{};
    vpv.x = 0.f; vpv.y = 0.f;
    vpv.width  = (float)m_extent.width;
    vpv.height = (float)m_extent.height;
    vpv.maxDepth = 1.f;
    vkCmdSetViewport(m_cmdBuf, 0, 1, &vpv);
    VkRect2D sc{ {0,0}, m_extent };
    vkCmdSetScissor (m_cmdBuf, 0, 1, &sc);

    // Branch por modo: asset (triángulos sólidos + depth test) o legacy
    // motor (líneas, sin depth).  Mutuamente excluyente.
    if (m_assetActive && m_assetIndexCount > 0) {
        // Vertex/index buffers + push constants comunes a Solid y Wire.
        VkDeviceSize offs = 0;
        vkCmdBindVertexBuffers(m_cmdBuf, 0, 1, &m_assetVbo, &offs);
        vkCmdBindIndexBuffer(m_cmdBuf, m_assetIbo, 0, VK_INDEX_TYPE_UINT32);

        float pc[36];   // 16 + 16 + 4 floats = 144 bytes
        std::memcpy(pc,      vp.data(),    16 * sizeof(float));
        std::memcpy(pc + 16, model.data(), 16 * sizeof(float));
        pc[32] = m_assetTint[0];
        pc[33] = m_assetTint[1];
        pc[34] = m_assetTint[2];
        pc[35] = 1.0f;   // reservado
        vkCmdPushConstants(m_cmdBuf, m_solidPipeLayout,
                           VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                           0, sizeof(pc), pc);

        // Solid o Both: dibuja triángulos rellenos primero.
        if (m_assetMode == AssetRenderMode::Solid ||
            m_assetMode == AssetRenderMode::Both) {
            vkCmdBindPipeline(m_cmdBuf, VK_PIPELINE_BIND_POINT_GRAPHICS, m_solidPipeline);
            vkCmdDrawIndexed(m_cmdBuf, m_assetIndexCount, 1, 0, 0, 0);
        }
        // Wire o Both: dibuja las aristas (con depth bias para no z-fight).
        // En modo Both oscurecemos el tint para que las aristas contrasten
        // con el relleno; en modo Wire dejamos el tint normal.
        if (m_assetMode == AssetRenderMode::Wire ||
            m_assetMode == AssetRenderMode::Both) {
            if (m_assetMode == AssetRenderMode::Both) {
                float pcWire[36];
                std::memcpy(pcWire, pc, sizeof(pc));
                pcWire[32] = m_assetTint[0] * 0.25f;
                pcWire[33] = m_assetTint[1] * 0.25f;
                pcWire[34] = m_assetTint[2] * 0.25f;
                vkCmdPushConstants(m_cmdBuf, m_solidPipeLayout,
                                   VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                                   0, sizeof(pcWire), pcWire);
            }
            vkCmdBindPipeline(m_cmdBuf, VK_PIPELINE_BIND_POINT_GRAPHICS, m_wirePipeline);
            vkCmdDrawIndexed(m_cmdBuf, m_assetIndexCount, 1, 0, 0, 0);
        }
    } else {
        vkCmdBindPipeline(m_cmdBuf, VK_PIPELINE_BIND_POINT_GRAPHICS, m_pipeline);
        VkDeviceSize offs = 0;
        vkCmdBindVertexBuffers(m_cmdBuf, 0, 1, &m_vbo, &offs);

        float pc[32];
        std::memcpy(pc,      vp.data(),    16 * sizeof(float));
        std::memcpy(pc + 16, model.data(), 16 * sizeof(float));
        vkCmdPushConstants(m_cmdBuf, m_pipeLayout,
                           VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(pc), pc);
        vkCmdDraw(m_cmdBuf, m_vertexCount, 1, 0, 0);
    }

    vkCmdEndRenderPass(m_cmdBuf);
    vkEndCommandBuffer(m_cmdBuf);

    VkSubmitInfo si{};
    si.sType              = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers    = &m_cmdBuf;
    vkQueueSubmit(m_ctx->graphicsQueue(), 1, &si, m_fence);
}
